import { useConfig } from "@/context/useConfigContext";
import { useTheme } from "next-themes";
import { useRef, type ReactNode } from "react";
import { strokeColor } from "./constant";
import { cn } from "@/lib/utils";
import { Copy, Trash } from "lucide-react";
import { useCanvasManagerContext } from "@/context/useCanvasManager";
import { useSelectedShape } from "@/context/useSelectedShape";
import { AddShapeCommand, RemoveShapeCommand } from "@/canvas/UndoAndRedoCmd/ShapeCommand";
import { TOOLS_NAME } from "@/types/toolsTypes";
import type { Shape, RectShape, TextShape, EclipseShape, LineShape, RightArrowShape, DiamondShape, PenShape, PenArrayShape } from "@/types/canvasTypes";

export const StrokeColorLayout = () => {
  const { resolvedTheme } = useTheme();
  const { config, handleConfigChange } = useConfig();
  const colorPickerRef = useRef<HTMLInputElement>(null);

  const handleColorChange = (color: string) => {
    handleConfigChange({ ...config, stroke: color });
  };

  return (
    <div className="flex flex-col gap-2">
      <ConfigBarHeading>Stroke Color</ConfigBarHeading>
      <div className="flex items-center gap-2">
        {(resolvedTheme === "light" || resolvedTheme === "dark") &&
          strokeColor[resolvedTheme].map((color, index) => (
            <div
              onClick={() => handleColorChange(color)}
              key={index}
              className={cn(
                "h-6 w-6 cursor-pointer rounded-md border border-gray-300 transition-all ease-in-out hover:scale-110 dark:border-gray-600",
                config.stroke === color
                  ? `ring-1 ring-offset-1 ring-[${color}]`
                  : "",
              )}
              style={{ background: color }}
              title={color}
            />
          ))}
        <div
          onClick={() => {
            if (colorPickerRef.current) {
              colorPickerRef.current.click();
            }
          }}
          style={{ background: config.stroke }}
          className="h-7 w-7 cursor-pointer rounded-md border border-gray-300 transition-all ease-in-out hover:scale-110 dark:border-gray-600"
          title="Custom Color"
        />
      </div>
      <input
        type="color"
        className="hidden"
        ref={colorPickerRef}
        onChange={(e) => handleColorChange(e.target.value)}
        value={config.stroke}
      />
    </div>
  );
};

// Action Buttons (Delete & Duplicate)
export const ActionButtons = () => {
  const {canvasManager} = useCanvasManagerContext()
  const {executeCmd} = canvasManager
  const {selectedShape} = useSelectedShape();

  const handleDelete = () => {
    if(selectedShape){
      executeCmd(new RemoveShapeCommand(canvasManager, selectedShape))
    }
  }

  const handleDuplicate = () => {
    if (selectedShape) {
      let duplicatedShape: Shape;
  
      switch (selectedShape.type) {
        case TOOLS_NAME.TEXT: {
          const shape = selectedShape as TextShape;
          duplicatedShape = {
            ...shape,
            id: undefined, // Will be generated by AddShapeCommand
            x: shape.x + 20,
            y: shape.y + 20,
          };
          break;
        }
  
        case TOOLS_NAME.RECT: {
          const shape = selectedShape as RectShape;
          duplicatedShape = {
            ...shape,
            id: undefined,
            x: shape.x + 20,
            y: shape.y + 20,
          };
          break;
        }
  
        case TOOLS_NAME.ECLIPSE: {
          const shape = selectedShape as EclipseShape;
          duplicatedShape = {
            ...shape,
            id: undefined,
            x: shape.x + 20,
            y: shape.y + 20,
          };
          break;
        }
  
        case TOOLS_NAME.LINE: {
          const shape = selectedShape as LineShape;
          duplicatedShape = {
            ...shape,
            id: undefined,
            x1: shape.x1 + 20,
            y1: shape.y1 + 20,
            x2: shape.x2 + 20,
            y2: shape.y2 + 20,
          };
          break;
        }
  
        case TOOLS_NAME.RIGHT_ARROW: {
          const shape = selectedShape as RightArrowShape;
          duplicatedShape = {
            ...shape,
            id: undefined,
            startX: shape.startX + 20,
            startY: shape.startY + 20,
            endX: shape.endX + 20,
            endY: shape.endY + 20,
          };
          break;
        }
  
        case TOOLS_NAME.DIAMOND: {
          const shape = selectedShape as DiamondShape;
          duplicatedShape = {
            ...shape,
            id: undefined,
            x: shape.x + 20,
            y: shape.y + 20,
          };
          break;
        }
  
        case TOOLS_NAME.PEN: {
          const shape = selectedShape as PenShape;
          duplicatedShape = {
            ...shape,
            id: undefined,
            lineArray: shape.lineArray.map(([x, y]) => [x + 20, y + 20] as PenArrayShape),
          };
          break;
        }
  
        default:
          return; 
      }
  
      executeCmd(new AddShapeCommand(canvasManager, duplicatedShape));
    }
  };

  if(!selectedShape){
    return <></>
  }

  return (
    <div className="flex w-full flex-col gap-2">
      <ConfigBarHeading>Actions</ConfigBarHeading>
      <div className="flex w-full gap-2">
        <button
          onClick={handleDelete}
          className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-md bg-destructive p-1 text-destructive-foreground shadow-md "
          title="Delete Selected Element"
        >
          <Trash size={16} /> {/* Increased icon size for better visibility */}
        </button>
        <button
          onClick={handleDuplicate}
          className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-md bg-accent p-1 text-accent-foreground shadow-md transition-colors"
          title="Duplicate Selected Element"
        >
          <Copy size={16} /> {/* Increased icon size */}
        </button>
      </div>
    </div>
  );
};

export const Button = ({
  children,
  className = "",
  altText,
  onClick,
}: {
  children: ReactNode;
  className?: string;
  altText: string;
  onClick?: () => void;
}) => {
  return (
    <button
      onClick={onClick}
      title={altText}
      className={cn(
        "border-border flex h-8 w-8 cursor-pointer items-center justify-center rounded-md border transition-colors",
        className,
      )}
    >
      {children}
    </button>
  );
};

export const ConfigBarHeading = ({ children }: { children: ReactNode }) => {
  return <h1 className="text-sidebar-foreground text-xs">{children}</h1>;
};
